# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='files',
            new_name='file_names',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='name',
            new_name='session_name',
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
