# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181111_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='email',
        ),
    ]
