# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-11 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_session_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='file_names',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='session_name',
            new_name='name',
        ),
    ]
